version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - app_network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend-service
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=password
      - SERVER_HOST=postgres
      - SERVER_PORT=5432
      - DB_NAME=postgres
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - app_network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    ports:
      - "3000:4173"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge